In [17]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
import pickle

In [18]:
df = pd.read_csv('/content/data_A.csv')

In [19]:
df.head()

,Unnamed: 0,id,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,churn
0,0,7317,15637411,Tochukwu,749.0,France,Male,30.0,1,0.00,2,0,0,126551.65,1
1,1,11125,15745307,Martin,683.0,Germany,Male,32.0,7,121887.91,1,1,1,176570.46,0
2,2,45720,15677382,Aitken,711.0,Spain,Female,33.0,5,0.00,2,1,0,162703.80,0
3,3,74042,15694450,Tuan,722.0,France,Female,28.0,4,0.00,2,1,1,76615.31,0
4,4,109985,15734987,Aitken,754.0,France,Female,67.0,3,0.00,2,1,1,114514.92,0

In [20]:
df.tail()

,Unnamed: 0,id,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,churn
41253,41253,52916,15756850,Hsieh,683.0,Germany,Female,29.0,9,125552.82,1,1,0,173948.30,1
41254,41254,22343,15714355,Hsing,610.0,Germany,Female,39.0,6,111760.40,2,1,0,120135.62,0
41255,41255,80083,15578098,Jamieson,600.0,France,Male,31.0,3,0.00,2,1,1,121555.51,0
41256,41256,79853,15682467,Ts'ui,648.0,Spain,Female,46.0,1,0.00,1,1,1,170528.63,0
41257,41257,16486,15805261,Howell,537.0,France,Female,47.0,7,0.00,1,0,1,52337.97,0

In [28]:
from sklearn.preprocessing import LabelEncoder

# Contoh data
data = ['Geography', 'Gender']
encoded_df = df

# Inisialisasi objek LabelEncoder
label_encoder = LabelEncoder()

# Fit dan transformasi data menggunakan LabelEncoder
for i in data:
  encoded_df[i] = label_encoder.fit_transform(df[i])

In [31]:
encoded_df.drop(columns=['Surname', 'id', 'Unnamed: 0', 'CustomerId'], axis=1, inplace=True)

In [33]:
encoded_df.isnull().sum()

CreditScore        20
Geography           0
Gender              0
Age                 0
Tenure              0
Balance             0
NumOfProducts       0
HasCrCard           0
IsActiveMember      0
EstimatedSalary     0
churn               0
dtype: int64

In [35]:
encoded_df['CreditScore'] = encoded_df['CreditScore'].fillna(value=encoded_df['CreditScore'].median())

In [36]:
X = encoded_df.drop('churn', axis=1)  # Ganti 'target_column' dengan nama kolom target Anda
y = encoded_df['churn']

# Bagi data menjadi data latih dan data uji
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Latih model Random Forest
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

# Lakukan prediksi dengan model Random Forest
rf_pred = rf_model.predict(X_test)

# Evaluasi kinerja Random Forest
rf_accuracy = accuracy_score(y_test, rf_pred)
print("Random Forest Accuracy:", rf_accuracy)

# Latih model XGBoost
xgb_model = XGBClassifier()
xgb_model.fit(X_train, y_train)

# Lakukan prediksi dengan model XGBoost
xgb_pred = xgb_model.predict(X_test)

# Evaluasi kinerja XGBoost
xgb_accuracy = accuracy_score(y_test, xgb_pred)
print("XGBoost Accuracy:", xgb_accuracy)

# Bandingkan kinerja kedua model dan simpan model terbaik menggunakan pickle
if rf_accuracy > xgb_accuracy:
    best_model = rf_model
    print("Model terbaik adalah Random Forest")
else:
    best_model = xgb_model
    print("Model terbaik adalah XGBoost")

# Simpan model terbaik dalam format pickle
with open('best_model.pkl', 'wb') as f:
    pickle.dump(best_model, f)

Random Forest Accuracy: 0.8639117789626757
XGBoost Accuracy: 0.8631846825012118
Model terbaik adalah Random Forest